# 本ワークフローの名前
name: Python application test with Github Actions
# これはこのJobがトリガーされるタイミング
on: [push] 

jobs:
  # Jobの名前
  build:
    # 実行仮想環境の指定
    runs-on: ubuntu-latest
    # ワーキングディレクトリの設定
    defaults:
      run:
        working-directory: ./week01/AWS
    steps:
      # 各コマンドの実行は，predifinedのものならusesで指定コマンドならrunで行う．
      - uses: actions/checkout@v2
      - name: Python3.8のセットアップ
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 依存パッケージのインストール
        run: |
          make install
      - name: Pylintによる静的解析
        run: |
          make lint
      - name: Pytestによる単体テスト
        run: |
          make test
      - name: Python blackによる整形
        run: |
          make format
